name: Build on RPi5

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Build project
      run: |
        mkdir -p build
        cd build
        cmake ..
        make -j4
    - name: Run executable (optional test run)
      run: ./build/camera_memtest